### ISSUE TITLE
Icons still showing up when deactivated or uninstalled

### ISSUE THREAD

**Issue by tedr56** [psychobunny/nodebb-plugin-designer#1]
Very strange, but this is what I get :
![pix](https://i.imgur.com/OgUfXBW.png)

**Comment by psychobunny** [comment]
after clearing cache, it still shows up?

**Comment by tedr56** [comment]
It did but it's gone since reboot.
Pretty sure the cache was cleared.

**Comment by tedr56** [comment]
Actually, I restarted the server today, and it's back.
